# Generated by Django 4.2 on 2024-05-14 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0008_withdrawmodel_user_link_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=20)),
                ('b', models.CharField(max_length=20)),
                ('c', models.CharField(max_length=20)),
                ('room', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('roundno', models.IntegerField(blank=True, default=None, null=True)),
                ('total', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('bear', 'BEAR'), ('bull', 'BULL'), ('single', 'SINGLE'), ('twin', 'TWIN')], default='bear', max_length=20)),
                ('amount', models.IntegerField()),
                ('room', models.IntegerField(default=None)),
                ('roundno', models.IntegerField()),
                ('result', models.CharField(choices=[('pending', 'PENDING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
